name: Build and Release Gem
on:
  push:
    branches: ['**']
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build Gem
    runs-on: ubuntu-latest
    outputs:
      semantic-version: ${{ steps.determine-version.outputs.SemVer }}
      pre-release-label: ${{ steps.determine-version.outputs.PreReleaseLabel }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '6.0.x'
      - name: Determine Version
        id: determine-version
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          useConfigFile: true
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: bundle install
      - name: Update .gemspec version
        run: |
          sed -i "s/\(spec\.version\s*=\s*\)['\"].*['\"]/\1'${{ steps.determine-version.outputs.SemVer }}'/" *.gemspec
      - name: Build gem
        run: gem build *.gemspec
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: '*.gem'
          name: gem
  test:
    name: Test Gem
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        # Add this under the 'test' job, right after 'Set up Ruby'
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install MathJax
        run: npm install mathjax-full
      - name: Install dependencies
        run: bundle install
      - name: Install Diff_PDF
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install make automake g++
          sudo apt-get install libpoppler-glib-dev poppler-utils libwxgtk3.2-dev

          # Download diff-pdf code
          wget https://github.com/vslavik/diff-pdf/archive/refs/tags/v0.5.2.tar.gz -O diff-pdf-0.5.2.tar.gz \
            && tar -xzf diff-pdf-0.5.2.tar.gz \
            && rm diff-pdf-0.5.2.tar.gz

          # Build and install diff-pdf
          cd diff-pdf-0.5.2 \
            && ./bootstrap \
            && ./configure \
            && make \
            && sudo make install
      - name: Install and Start Xvfb (artificial display server)
        run: |
          sudo apt-get install xvfb
          Xvfb :99 -screen 0 1024x768x24 &      # Start Xvfb in the background
          echo "DISPLAY=:99" >> $GITHUB_ENV     # Set DISPLAY for subsequent steps
          echo "NO_AT_BRIDGE=1" >> $GITHUB_ENV  # Disable AT-SPI
      - name: Run tests
        run: ruby test/test_*.rb
      - name: Upload test artifacts (if failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: |
            test/verification/*.diff.pdf
            test/verification/*.received.pdf
          name: test-results
  release:
    name: Release Gem
    needs: [build, test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: gem
      - name: Create a Release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{needs.build.outputs.semantic-version}}"
          release_name: "v${{needs.build.outputs.semantic-version}}"
          prerelease: ${{ needs.build.outputs.pre-release-label != '' }}
      - name: Publish gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: gem push *.gem
